### ISSUE TITLE
Write a giant primal-primal MPS file

### ISSUE THREAD

**Issue by odow** [joaquimg/BilevelJuMP.jl#113]
A key milestone for MiBS is to write a giant primal-primal MPS file.

- Write a function that takes a bilevel problem and makes a new MOI primal-primal problem
- Write a function that writes this model to MPS (Just use `MOI.FileFormats.MPS`)
- Write a function that writes out the auxiliary file

@matbesancon has a reader for these files somewhere

**Comment by odow** [comment]
Pyomo has an interface to MibS:
https://github.com/or-fusion/pao/blob/b428263039c5953d39e4b14147cad27f27874be1/pao/mpr/solvers/mibs.py

**Comment by odow** [comment]
@HesamShaelaie the next step to hooking up MibS is to write a function that takes the upper and the lower, and returns a single model containing both.

We also need a list of the lower and upper variables, and the lower objective

```Julia
function _build_single_model(
    upper::MOI.ModelLike, 
    lower::MOI.ModelLike, 
    # A dictionary that maps variables in the upper to variables in the lower
    link::Dict{MOI.VariableIndex,MOI.VariableIndex},
)
    # A new model to build
    model = MOI.Utilities.Model{Float64}()
    # Create a copy of the upper model
    index_map = MOI.copy_to(model, upper)
    # TODO ... add the lower problem to `model`
    return model, upper_variables, lower_variables, lower_objective
end
```

Here's something similar to the function we have
https://github.com/joaquimg/BilevelJuMP.jl/blob/82d533037fa2117f8918954836295db572ee26c2/src/moi.jl#L269-L396

This is where it gets called from
https://github.com/joaquimg/BilevelJuMP.jl/blob/82d533037fa2117f8918954836295db572ee26c2/src/jump.jl#L367-L389

Here are the fields in a `BilevelModel`
https://github.com/joaquimg/BilevelJuMP.jl/blob/82d533037fa2117f8918954836295db572ee26c2/src/jump.jl#L10-L32

**Comment by odow** [comment]
```Julia
lower_variables = MOI.get(lower, MOI.ListOfVariableIndices())
new_lower_variables = MOI.add_variables(model, length(lower_variables))
```

**Comment by odow** [comment]
```Julia
for (F, S) in MOI.get(lower, MOI.ListOfConstraints())
    # ...
end
```

**Comment by joaquimg** [comment]
I think we should use append_to.
We can have a second issue to simplify append_to to use add constraint instead of pass constraint.

We should still try to constrain variables on creation.

We still need to pass var attributes like names.

**Comment by odow** [comment]
We're going to have a problem where the auxiliary file needs to the rows of the constraints in the lower problem. I don't think the MPS writer has a way of getting this information.

**Comment by HesamShaelaie** [comment]
Why do we need to create one gigantic model first and convert it to MPS and Aux? Why not just get the bilevel model and create the MPS and Aux? in this way, we know the upper and lower constraints separately, and we don't have the indexing problem for the constraints. Am I right?

**Comment by matbesancon** [comment]
The unified model is what gets written to MPS. If you try to write to MPS the bilevel model itself, you might not have all constraints appearing.
Otherwise you can always do some tests, try to write the bilevel model to MPS directly and see if everything is correct when reading it back (i.e. if you have what would be the giant unified model)

**Comment by odow** [comment]
We're pretty close on getting the full problem. Once we have that, it's just:
```Julia
MOI.write_to_file(model, "problem.mps")
```
Duplicating the MPS writer seems like more work.

**Comment by odow** [comment]
The row- and column-mapping is pretty trivial. It's just:
```Julia
"""
    index_to_row_link(model::MOI.FileFormats.MPS.Model)

Returns a dictionary that maps the affine constraint indices of `model` to their
row in the MPS file.
"""
function index_to_row_link(model::MOI.FileFormats.MPS.Model)
    i = 0
    dict = Dict{MOI.ConstraintIndex,Int}()
    for (S, _) in MOI.FileFormats.MPS.SET_TYPES
        for ci in MOI.get(
            model,
            MOI.ListOfConstraintIndices{MOI.ScalarAffineFunction{Float64},S}(),
        )  
            dict[ci] = i
            i += 1
        end
    end
    return dict
end

"""
    index_to_column_link(model::MOI.FileFormats.MPS.Model)

Returns a dictionary that maps the variable indices of `model` to their column 
in the MPS file.
"""
function index_to_row_link(model::MOI.FileFormats.MPS.Model)
    variables = MOI.get(model, MOI.ListOfVariableIndices())
    return Dict{MOI.VariableIndex,Int}(
        x => i - 1 for (i, x) in MOI.enumerate(variables)
    )
end
```

We don't need to wait for this to be added to MOI

**Comment by odow** [comment]
Code for testing auxiliary files
```Julia
function write_aux(filename)
    open(filename, "w") do io
        println(io, "Hello World!")
    end
end

@testset "Test" begin
    write_aux("test.aux")
    answer = read("answer.aux", String)
    test = read("test.aux", String)
    @test test == answer
end
```

**Comment by odow** [comment]
Closing as done by #124
