### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by odow** [joaquimg/BilevelJuMP.jl#120]
@joaquimg CI failed with some tolerance issue https://github.com/joaquimg/BilevelJuMP.jl/runs/2770040699

**Comment by joaquimg** [comment]
Yup, that is the new version of SCIP used in tests.
The best solution would be to add a project.toml to the test folder.
The drawback would be dropping 1.0 CI
What's your take?

**Comment by odow** [comment]
I'm fine dropping all support for 1.0 :) Make it 1.6, and change the documentation also? MibS is going to be 1.6+ only as well.

**Comment by joaquimg** [comment]
closed by #122

**Comment by joaquimg** [comment]
This was already in 1.4 due SCIP's jll's
