### ISSUE TITLE
Add extra (useless) binary variable in SOS1 (Cbc's bug)

### ISSUE THREAD

**Issue by joaquimg** [joaquimg/BilevelJuMP.jl#123]
see https://github.com/joaquimg/BilevelJuMP.jl/pull/121

**Comment by odow** [comment]
We should fix this at the Cbc level. Working on it now.

**Comment by odow** [comment]
Hmm. This might actually take a new release of Cbc. It assumes that _all_ variables in the SOS are binary.

**Comment by joaquimg** [comment]
If all variable must be binaries it won't work.
The SOS formulation is used because it requires no bounds.
Otherwise it is fortuny amat

**Comment by joaquimg** [comment]
This seems identical to: https://github.com/jump-dev/Cbc.jl/issues/151
Can we close this one in favor of the Cbc.jl one?
