### ISSUE TITLE
🏴‍☠️🏴‍☠️🏴‍☠️ Tests break precompilation 🏴‍☠️🏴‍☠️🏴‍☠️

### ISSUE THREAD

**Issue by odow** [joaquimg/BilevelJuMP.jl#128]
Why is this needed?

https://github.com/joaquimg/BilevelJuMP.jl/blob/23073d55ac0d9bd818b41af73cf7e076f34264e2/src/jump_nlp.jl#L111-L121

**Comment by joaquimg** [comment]
Probably not needed.
I will comment it out and see if things break.

**Comment by odow** [comment]
I'm so pleased I remembered Github supports emoji titles haha
