### ISSUE TITLE
🏴‍☠️🏴‍☠️🏴‍☠️ JuMP.index is pirated 🏴‍☠️🏴‍☠️🏴‍☠️

### ISSUE THREAD

**Issue by odow** [joaquimg/BilevelJuMP.jl#143]
https://github.com/joaquimg/BilevelJuMP.jl/blob/4b2839e6e00ede959494ad6998e389a92d2b0f81/src/jump.jl#L209-L216

**Comment by joaquimg** [comment]
good catch, that is probably an easy fix, probably just renaming.
