### ISSUE TITLE
Puzzled by how to use package for this simple example

### ISSUE THREAD

**Issue by innuo** [joaquimg/BilevelJuMP.jl#144]
To solve the following (minimal-example) bilevel problem
```
min_y x
s.t. x = argmax_x x
       s.t. 0 <= x <= 1
```
I am implementing it as 
```
model = BilevelModel(Cbc.Optimizer, mode = BilevelJuMP.SOS1Mode())
@variable(Upper(model), y)
@variable(Lower(model), 0 <= x <= 1)
@objective(Upper(model), Min, x)
@objective(Lower(model), Max, x)
@time optimize!(model)

@show value(x)
```

which produces
`value(x) = 0.0`

Which is clearly wrong because the lower optimization should constrain `x` to be `1`.  

I would appreciate any suggestions on what I am doing wrong.

ps. I tried switching `x` to be an upper variable to no avail.

**Comment by innuo** [comment]
Here is a solution of the above problem with explicit KKT formulation:

```
model = Model(Cbc.Optimizer)
@variable(model, y)
@variable(model, 0 <= x <= 1)
@variable(model, 0 <= dual_up)
@variable(model, 0 <= dual_down)
@variable(model, z_up, Bin)            #binaries to enforce complementarity
@variable(model, z_down, Bin)       #binaries to enforce complementarity


@constraint(model, dual_up - dual_down == 1) # first order stationarity
M = 10
@constraint(model, -M * z_up <= x - 1)
@constraint(model,  M * z_up >= x - 1)
@constraint(model, -M * (1-z_up) <= dual_up)
@constraint(model,  M * (1-z_up) >= dual_up)

@constraint(model, -M * z_down <= x)
@constraint(model,  M * z_down >= x)
@constraint(model, -M * (1-z_down) <= dual_down)
@constraint(model,  M * (1-z_down) >= dual_down)

optimize!(model)
@show value(x)
```
which, as expected produces 
`value(x) = 1.0`

**Comment by odow** [comment]
> model = BilevelModel(Cbc.Optimizer, mode = BilevelJuMP.SOS1Mode())

Did Cbc print a warning about known bugs in SOS? There is an upstream bug in Cbc: https://github.com/coin-or/Cbc/issues/363

**Comment by innuo** [comment]
@odow Yes, indeed it did. In fact the warning is thrown also for the example on the BilevelJuMP.jl github page. 
```
Warning: There are known correctness issues using Cbc with SOS constraints and no binary variables.
@ Cbc ~/.julia/packages/Cbc/JdG60/src/MOI_wrapper/MOI_wrapper.jl:716
```
Any workarounds you would recommend?

**Comment by innuo** [comment]
I added the following innocuous line to the problem and now it works fine. Will do this until a fix is implemented. 
`@variable(Upper(model), dummy, Bin)`

**Comment by odow** [comment]
The dummy binary variable is one approach.

If you're an academic, you can obtain an academic license to Gurobi or CPLEX. They are much preferred to Cbc.
