### ISSUE TITLE
Different solutions for same problem with Cbc and Gurobi solvers

### ISSUE THREAD

**Issue by keatsig** [joaquimg/BilevelJuMP.jl#155]
I am trying to solve a simple problem using BilevelJuMP and Cbc/Gurobi solvers. The problem is similar to the example discussed in JuliaCon2021:

```
m = BilevelModel(Cbc.Optimizer, mode=BilevelJuMP.SOS1Mode())
#m = BilevelModel(Gurobi.Optimizer, mode=BilevelJuMP.SOS1Mode())
@variable(Upper(m), x )
@variable(Lower(m), y )

@constraint(Lower(m), c1, 2x+y ≤ 4 )
@constraint(Lower(m), c2, x+2y ≤ 4 )
@constraint(Lower(m), c3, x ≥ 0 )
@constraint(Lower(m), c4, y ≥ 0 )

@objective(Upper(m), Min, -4x-3y )
@objective(Lower(m), Min, y )
```
When I use Cbc, the objective value is -9.33 with x=1.33 and y=1.33.
When I use Gurobi, the objective value is -8 with x=2 and y=0. 
If I solve the single level reduction of the problem using Ipopt, I get the same solution as Gurobi. 
I was wondering if the difference in solutions between Cbc and Gurobi is a bug in BilevelJuMP or if its related to correctness issues using Cbc with SOS constraints.

**Comment by guilhermebodin** [comment]
Could you provide a status of the Manifest.toml (`st --manifest`) you are using? There is a bug with Dualization 0.3.5 that might be causing it.

**Comment by keatsig** [comment]
I am using Dualization 0.3.5. Here is the Manifest.toml:
[Manifest.zip](https://github.com/joaquimg/BilevelJuMP.jl/files/7488439/Manifest.zip)

**Comment by guilhermebodin** [comment]
Could you try to run with Dualization at version 0.3.4
```julia
pkg> rm BilevelJuMP
pkg> add Dualization@0.3.4
pkg> pin Dualization
pkg> add BilevelJuMP
```
If it still fails it is probably a Cbc correctness issue.

**Comment by joaquimg** [comment]
The Cbc solution is wrong.

Note that if x = 1.33 is the solution of the upper level, the lower level problem would still be able to drag y to 0. Since the lower level does not optimize x, the lower level considers x as a parameter.

Probably due to a bug in the latest versions of CBC: https://github.com/jump-dev/Cbc.jl/issues/151

**Comment by odow** [comment]
Yes, there is a known correctness issue in Cbc, and the package will print a warning telling you so.
