### ISSUE TITLE
Xpress tests not running in CI/Actions

### ISSUE THREAD

**Issue by NLaws** [joaquimg/BilevelJuMP.jl#167]
I have searched the Actions logs for "xpress"on master branch and in my [PR](https://github.com/joaquimg/BilevelJuMP.jl/pull/157): it appears that this line is not reached:
https://github.com/joaquimg/BilevelJuMP.jl/blob/c60d8ea2794c5ae39787cdd389acebddd8e34ab0/test/runtests.jl#L58
I think that having Xpress tests will increase my PR's codecov percentage (if I correctly understand how codecov works).

**Comment by NLaws** [comment]
@joaquimg What do you think of running tests on Mac in Actions (in addition to on Windows as you are now). It would make it easier for me (and other Mac developers) to contribute and it will help with cross-platform compatibility of this package.

**Comment by odow** [comment]
It's because of this:
https://github.com/joaquimg/BilevelJuMP.jl/blob/c60d8ea2794c5ae39787cdd389acebddd8e34ab0/test/runtests.jl#L57

@joaquimg can correct me, but I think we only have permission to install Xpress in repos under JuMP-dev.

**Comment by joaquimg** [comment]
We only have permission to access the secrets on this particular repo.
I got permission from FICO to use in jump-dev org.

**Comment by joaquimg** [comment]
Mac developers should be able to run locally with the `XPRESSDIR` env variable. As for maintaining multiplatform CI. That is more complicated because I can't commit to that.

As for your PR, it would only trigger express if you had owner permission. I will follow up on it in BilevelJuMP.

**Comment by NLaws** [comment]
Ok FYI I have been testing with Gurobi locally. How do you normally test all the different solvers? Are you doing that locally only?  (I can only use Xpress on my work computer).

**Comment by joaquimg** [comment]
I have been mostly testing locally. There is no reasonable open source solver with SOS1 constraints. Cbc is too unreliable for this.
