### ISSUE TITLE
error in solve_with_MibS 

### ISSUE THREAD

**Issue by karimianfard** [joaquimg/BilevelJuMP.jl#168]
Hello, I wrote the following code but I got the following error. please guide me.

Code is bellow:
=======================================
using BilevelJuMP
using JuMP
using MibS_jll

model = BilevelModel()

# First we need to create all of the variables in the upper and lower problems:

# Upper level variables
@variable(Upper(model), x, Int)
@variable(Upper(model), z, Bin)

#Lower level variables
@variable(Lower(model), y)

# Then we can add the objective and constraints of the upper problem:

# Upper level objecive function
@objective(Upper(model), Min, 2x - 4y + 10z)

# Upper constraints
@constraints(Upper(model), begin
    u1, -3x + 2y + 5z  <= 12
    u2, x + 2y <= 20
    u3, x <= 10
end)

# Followed by the objective and constraints of the lower problem:

# Lower objective function
@objective(Lower(model), Min, y)

# Lower constraints
@constraint(Lower(model), l1,  2x -  y + 3z <= 7)
@constraint(Lower(model), l2, -2x +  4y <= 16)
@constraint(Lower(model), l3, y <= 5)
solution = BilevelJuMP.solve_with_MibS(model, MibS_jll.mibs, silent = true)

============================
result is bellow:
UndefVarError: solve_with_MibS not defined

Stacktrace:
 [1] getproperty(x::Module, f::Symbol)
   @ Base .\Base.jl:26
 [2] top-level scope
   @ In[29]:37
 [3] eval
   @ .\boot.jl:360 [inlined]
 [4] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
   @ Base .\loading.jl:1116

**Comment by joaquimg** [comment]
There is no released version with MibS support, you might want to try checking out on master

```julia
import Pkg
Pkg.add(url="https://github.com/joaquimg/BilevelJuMP.jl", rev="master")
```

However, your example **only has integer variables in the upper level**, in that case you can use a standard MIP solver like HiGHS, GLPK, Xpress, CPLEX, Gurobi...

Moreover,  MibS requires that lower lever variables are also integer, so, even if you download master, that example will not work.

**Comment by tkralphs** [comment]
MibS only requires the linking variables (upper-level variables that participate in lower-level constraints) to be integer-valued, although I have to admit that I don't think we have any test cases in which all lower-level variables are continuous. I'd be curious to know if this works as it should. I'm getting ready to release a new stable version of MibS that has a bunch of small bug fixes, so hopefully, we can get that incorporated here soon after release.

**Comment by karimianfard** [comment]
Thank you very much dear Ted and Joaquim

In fact, my main bi-level model has both binary and continuous variables at the lower and upper levels.
Normally the "BilevelJuMP" package can not solve the existence of a binary variable in the lower-level.
But in the description of the "MibS" package, it was written that if there is a binary variable at the lower level, it can solve it! But it still seems to have a problem.
The code is written as follows:

using JuMP, Gurobi, BilevelJuMP, MibS_jll

model = BilevelModel()
@variable(Upper(model), x, Int)
@variable(Lower(model), y, Bin)

@objective(Upper(model), Min, -3x - 7y)
@constraints(Upper(model), begin
     -3x + 2y <= 12
     x + 2y <= 20
     x <= 10
end)

@objective(Lower(model), Min, y)
@constraint(Lower(model),   2x -  y <= 7)
@constraint(Lower(model),  -2x +  4y <= 16)
@constraint(Lower(model),  y <= 5)

solution = BilevelJuMP.solve_with_MibS(model, MibS_jll.mibs, silent = true)

ERROR:Unable to read in instance
 from function readInstance
 from class MibSModel


Stacktrace:
 [1] error(s::String)
   @ Base .\error.jl:33
 [2] _call_mibs
   @ C:\Users\Hossein Karimianfard\.julia\packages\BilevelJuMP\GawB0\src\jump_input.jl:138 [inlined]
 [3] (::BilevelJuMP.var"#63#64"{Bool, Bool, BilevelModel, typeof(mibs)})(path::String)
   @ BilevelJuMP C:\Users\Hossein Karimianfard\.julia\packages\BilevelJuMP\GawB0\src\jump_input.jl:274
 [4] mktempdir(fn::BilevelJuMP.var"#63#64"{Bool, Bool, BilevelModel, typeof(mibs)}, parent::String; prefix::String)
   @ Base.Filesystem .\file.jl:729
 [5] mktempdir(fn::Function, parent::String) (repeats 2 times)
   @ Base.Filesystem .\file.jl:727
 [6] #solve_with_MibS#62
   @ C:\Users\Hossein Karimianfard\.julia\packages\BilevelJuMP\GawB0\src\jump_input.jl:253 [inlined]
 [7] top-level scope
   @ In[28]:19
 [8] eval
   @ .\boot.jl:360 [inlined]
 [9] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
   @ Base .\loading.jl:1116

**Comment by tkralphs** [comment]
MibS can handle general integer+continuous at both levels, as long as the linking variables are integer. 

That error means there was something wrong with the MPS file. Maybe @HesamShaelaie can take a look? @joaquimg is there a way to grab the MPS file that is being fed to MibS?

**Comment by joaquimg** [comment]
There is. I just made it easier in: https://github.com/joaquimg/BilevelJuMP.jl/pull/169 (so the model.mps and model.aux will be written in the user current dir).

However, I ran:
```julia
using JuMP, BilevelJuMP, MibS_jll

model = BilevelModel()
@variable(Upper(model), x, Int)
@variable(Lower(model), y, Bin)

@objective(Upper(model), Min, -3x - 7y)
@constraints(Upper(model), begin
-3x + 2y <= 12
x + 2y <= 20
x <= 10
end)

@objective(Lower(model), Min, y)
@constraint(Lower(model), 2x - y <= 7)
@constraint(Lower(model), -2x + 4y <= 16)
@constraint(Lower(model), y <= 5)

solution = BilevelJuMP.solve_with_MibS(model, MibS_jll.mibs)
```
It worked and returned:
```julia
solution = BilevelJuMP.solve_with_MibS(model, MibS_jll.mibs)
(status = true, objective = -19.0, nonzero_upper = Dict(0 => 4.0), nonzero_lower = Dict(0 => 1.0), all_upper = Dict{Any, Any}("x" => 4.0), all_lower = Dict{Any, Any}("y" => 1.0), all_var = Dict{Any, Any}(MathOptInterface.VariableIndex(2) => 1.0, MathOptInterface.VariableIndex(1) => 4.0))
```

@karimianfard , can you try the exact code I pasted?

If it fail with the same error you previously had, please run:
```julia
import Pkg; Pkg.status()
```
An paste the results here, mine are:
```julia
  [485130c0] BilevelJuMP v0.4.2 `https://github.com/joaquimg/BilevelJuMP.jl.git#master`
  [4076af6c] JuMP v0.21.10
  [118347d2] MibS_jll v100.100.301+0
  ```
  
I installed things with:
```julia
] add BilevelJuMP#master, MibS_jll, JuMP
```
If you want to star from a clean environment, you can do:
```julia
] activate my_env
```
before adding packages.

**Comment by karimianfard** [comment]
Dear @joaquimg thank you very much for your time and help. I copied the code exactly as you wrote it, but it gave the same error again. My installed packages are as follows:

  Status `C:\Users\Hossein Karimianfard\.julia\environments\v1.6\Project.toml`
  [485130c0] BilevelJuMP v0.4.2 `https://github.com/joaquimg/BilevelJuMP.jl#master`
  [9961bab8] Cbc v0.8.1
  [a93c6f00] DataFrames v1.3.3
  [2e9cd046] Gurobi v0.9.14
  [7073ff75] IJulia v1.23.3
  [b6b21f68] Ipopt v0.7.0
  [4076af6c] JuMP v0.21.10
  [91a5bcdd] Plots v1.27.5
  [d7431456] PowerModelsDistribution v0.13.3
  [014a38d5] QuadraticToBinary v0.2.4
  [fdbf4ff8] XLSX v0.7.9
  [118347d2] MibS_jll v1.1.3+0


Dear @joaquimg and @tkralphs , 
How can I write "model.mps" and "model.aux" files? I have not created such files! Is it not possible to run the program easily without such help files?

**Comment by joaquimg** [comment]
```julia
] add BilevelJuMP#jg/mibs, MibS_jll, JuMP
```
then
```julia
using JuMP, BilevelJuMP, MibS_jll

model = BilevelModel()
@variable(Upper(model), x, Int)
@variable(Lower(model), y, Bin)

@objective(Upper(model), Min, -3x - 7y)
@constraints(Upper(model), begin
-3x + 2y <= 12
x + 2y <= 20
x <= 10
end)

@objective(Lower(model), Min, y)
@constraint(Lower(model), 2x - y <= 7)
@constraint(Lower(model), -2x + 4y <= 16)
@constraint(Lower(model), y <= 5)

solution = BilevelJuMP.solve_with_MibS(model, MibS_jll.mibs, keep_files = true)
```
This will generate files in your current directory `pwd()`.
But again, be 100% sure that you have admin privileges, because MibS uses file based communication.

**Comment by tkralphs** [comment]
> But again, be 100% sure that you have admin privileges, because MibS uses file based communication.

By this, you mean that you need to have write access to the working directory, right? You don't need to `sudo` or anything like that, right? That would be a bit scary.

**Comment by joaquimg** [comment]
Yes, just need, read and write access in a directory.
But @karimianfard is on windows, so things are weird.

**Comment by karimianfard** [comment]
Dear @joaquimg , I entered the codes exactly. But it warns again.

UndefVarError: solve_with_MibS not defined

Stacktrace:
 [1] getproperty(x::Module, f::Symbol)
   @ Base .\Base.jl:26
 [2] top-level scope
   @ In[13]:19
 [3] eval
   @ .\boot.jl:360 [inlined]
 [4] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
   @ Base .\loading.jl:1116

**Comment by karimianfard** [comment]
Status `C:\Users\karim\.julia\environments\v1.6\Project.toml`
  [485130c0] BilevelJuMP v0.4.2
  [9961bab8] Cbc v0.8.1
  [a93c6f00] DataFrames v1.3.3
  [e9467ef8] GLMakie v0.5.5
  [2e9cd046] Gurobi v0.9.14
  [7073ff75] IJulia v1.23.3
  [b6b21f68] Ipopt v0.6.3
  [4076af6c] JuMP v0.21.10
  [ee78f7c6] Makie v0.16.6
  [91a5bcdd] Plots v1.27.5
  [014a38d5] QuadraticToBinary v0.2.4
  [fdbf4ff8] XLSX v0.7.9
  [118347d2] MibS_jll v100.100.301+0

**Comment by karimianfard** [comment]
Dear  @joaquimg, How to write "file.mps" and "file_auxiliary.txt" files for my model?

**Comment by joaquimg** [comment]
You are in the wrong branch.
you need to add packages like this:
```
] add BilevelJuMP#jg/mibs, MibS_jll, JuMP
```
the `#` is defining the branch

**Comment by karimianfard** [comment]
dear @joaquimg , please see the attached image. It does not work.
![image](https://user-images.githubusercontent.com/84530547/164065623-b7dd3530-bb93-4f8e-bd3f-bc4129b8b8fb.png)

Unable to parse `MibS_jll,` as a package.

Stacktrace:
  [1] pkgerror(msg::String)
    @ Pkg.Types C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\Types.jl:55
  [2] parse_package_identifier(word::String; add_or_develop::Bool)
    @ Pkg.REPLMode C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\REPLMode\argument_parsers.jl:135
  [3] parse_package_args(args::Vector{Union{Pkg.Types.VersionRange, String, Pkg.REPLMode.Rev, Pkg.REPLMode.Subdir}}; add_or_dev::Bool)
    @ Pkg.REPLMode C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\REPLMode\argument_parsers.jl:96
  [4] parse_package(args::Vector{Pkg.REPLMode.QString}, options::Dict{Symbol, Any}; add_or_dev::Bool)
    @ Pkg.REPLMode C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\REPLMode\argument_parsers.jl:11
  [5] (::Pkg.REPLMode.var"#64#69")(x::Vector{Pkg.REPLMode.QString}, y::Dict{Symbol, Any})
    @ Pkg.REPLMode C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\REPLMode\command_declarations.jl:95
  [6] Pkg.REPLMode.Command(statement::Pkg.REPLMode.Statement)
    @ Pkg.REPLMode C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\REPLMode\REPLMode.jl:366
  [7] iterate
    @ .\generator.jl:47 [inlined]
  [8] _collect(c::Vector{Pkg.REPLMode.Statement}, itr::Base.Generator{Vector{Pkg.REPLMode.Statement}, Type{Pkg.REPLMode.Command}}, #unused#::Base.EltypeUnknown, isz::Base.HasShape{1})
    @ Base .\array.jl:695
  [9] collect_similar
    @ .\array.jl:606 [inlined]
 [10] map
    @ .\abstractarray.jl:2294 [inlined]
 [11] do_cmd(repl::IJulia.MiniREPL, input::String; do_rethrow::Bool)
    @ Pkg.REPLMode C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\REPLMode\REPLMode.jl:383
 [12] top-level scope
    @ In[1]:1
 [13] eval
    @ .\boot.jl:360 [inlined]
 [14] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
    @ Base .\loading.jl:1116

**Comment by karimianfard** [comment]
Dear @joaquimg , answered! But I just typed this phrase "] add BilevelJuMP#jg/mibs".
I had two questions. How can I see the results of the problem? Like objective function and variables?
Can the "Gurobi" solver be used to solve the problem?

After running the output was as follows:
(status = true, objective = -19.0, nonzero_upper = Dict(0 => 4.0), nonzero_lower = Dict(0 => 1.0), all_upper = Dict{Any, Any}("x" => 4.0), all_lower = Dict{Any, Any}("y" => 1.0), all_var = Dict{Any, Any}(MathOptInterface.VariableIndex(2) => 1.0, MathOptInterface.VariableIndex(1) => 4.0))

**Comment by joaquimg** [comment]
1 - The result is in the struct `solution`, returned by `BilevelJuMP.solve_with_MibS(model, MibS_jll.mibs)` that you printed, you can get variable results from there.

2 - You cannot use Gurobi.
