### ISSUE TITLE
MibS fails to read .mps files with `OBJSENSE` key

### ISSUE THREAD

**Issue by joaquimg** [joaquimg/BilevelJuMP.jl#170]
These files break MibS
[w_model.aux.txt](https://github.com/joaquimg/BilevelJuMP.jl/files/8517370/w_model.aux.txt)
[w_model.mps.txt](https://github.com/joaquimg/BilevelJuMP.jl/files/8517372/w_model.mps.txt)

These work
[model.aux.txt](https://github.com/joaquimg/BilevelJuMP.jl/files/8517373/model.aux.txt)
[model.mps.txt](https://github.com/joaquimg/BilevelJuMP.jl/files/8517374/model.mps.txt)

`OBJSENSE MIN` line is the sole difference:
![image](https://user-images.githubusercontent.com/13870065/164126368-ba7bdc8a-f4fd-4d86-8739-a20e7530db6d.png)

Old MOI did not have that, new (1.0) has that. That is why it is breaking in some versions.

cc @tkralphs @odow

**Comment by odow** [comment]
Ah I hate MPS. `OBJSENSE` is a (mostly) standard addition. Traditional MPS files only support minimization, and you need to negative the objective coefficients for maximization. But it seemed like most solvers supported it, so we added it here: https://github.com/jump-dev/MathOptInterface.jl/pull/1391. I guess we can put it behind an option flag?

**Comment by joaquimg** [comment]
I would be fine with adding options, could be a solver attribute for the MPS model.

For now I am re-writing the file without that line: https://github.com/joaquimg/BilevelJuMP.jl/blob/33bbcb5ac6ad43e58d2c97bd48df62d71b388228/src/jump_input.jl#L79
And fixing signs: https://github.com/joaquimg/BilevelJuMP.jl/blob/33bbcb5ac6ad43e58d2c97bd48df62d71b388228/src/jump_input.jl#L60

MibS should try to handle that anyway.

**Comment by tkralphs** [comment]
Yes, [CoinUtils](https://github.com/coin-or/CoinUtils] sticks to the actual standard. One the one hand, that can be seen as annoying, but on the other hand, it also seems like a bad idea for developers to just unilaterally implement changes to the standard. It would be better if the main players would get together and agree on MPS v2. But anyway, feel free to open an issue in [CoinUtils](https://github.com/coin-or/CoinUtils]. I assume this would be an easy change.

**Comment by tkralphs** [comment]
Incidentally, this same issue would arise with any COIN-OR solver, since they all use [CoinUtils](https://github.com/coin-or/CoinUtils).

**Comment by odow** [comment]
I think Gurobi, CPLEX, and SCIP all support OBJSENSE, which makes it somewhat standard. We originally added it because MOI couldn't read models created by SCIP. But we should improve our "be permissive on reading, strict on writing."

**Comment by joaquimg** [comment]
This was solved with latest MOI that it the lower bound on BilevelJuMP version 0.5.1
