### ISSUE TITLE
JuMP 1.5

### ISSUE THREAD

**Issue by FabrizioLacalandra** [joaquimg/BilevelJuMP.jl#193]
I don't know if this is an issue or a pull request, however the installation of BJump seems to require a step back to JumP 1.1.1 (now 1.5). Is there any workaround or it is strictly needed?

Fabrizio

**Comment by joaquimg** [comment]
It it strictly needed because the Non-Linear programming internals in JuMP were updated and are incompatible as of now. It should not be hard fix though

**Comment by odow** [comment]
Duplicate of https://github.com/joaquimg/BilevelJuMP.jl/issues/178
