### ISSUE TITLE
Test on more platforms

### ISSUE THREAD

**Issue by odow** [joaquimg/BilevelJuMP.jl#197]
Tests only run on Windows v1.6:

https://github.com/joaquimg/BilevelJuMP.jl/blob/f38373bbda378f2fa86a27f87e704f5c3daa850b/.github/workflows/ci.yml#L15-L17

There are a few test failures on linux v1.9: https://github.com/jump-dev/JuMP.jl/actions/runs/5051033339/jobs/9062436458. Are these intended?

**Comment by joaquimg** [comment]
Currently, tests are on win because they use Xpress.
We should have some linux tests with SCIP even if ti means no testing as much

**Comment by joaquimg** [comment]
Linux fails are due to Ipopt not being super robust for some of these problems

**Comment by joaquimg** [comment]
closed by #198
