### ISSUE TITLE
Solve bilevel programming in KKT condition

### ISSUE THREAD

**Issue by OthmanProgramming** [joaquimg/BilevelJuMP.jl#206]
Min F(S_1,S_2,S_3 ):85 S_1+825S_2+125S_3            
           Min ʄ (S_1,S_2,S_3 ):825 S_1+800S_2+100S_3
st:                                                                                                       
500000S_1+436500S_2+386400S_3          ≤2322900           
13.186 S_1+12.321S_2+9.972S_3                    ≤400000           
12S_1+8S_2+5S_3                                                ≤2000                 
100000S_1+100000S_2+800000S_3          ≤1000800       
900S_1+850S_2+125S_3                                     ≤7650000        
S1,S2,S3≥0

**Comment by odow** [comment]
This doesn't appear to be a bilevel optimization problem because there is only a single set of variables.

Do you instead intend to solve a bi-objective optimization problem?

**Comment by OthmanProgramming** [comment]
> This doesn't appear to be a bilevel optimization problem because there is only a single set of variables.
> 
> Do you instead intend to solve a bi-objective optimization problem?

The problem that I have consists of a leader, a follower, and restrictions... There are no restrictions for the leader... only the follower... Yes, I want to solve it, how?

**Comment by OthmanProgramming** [comment]
I'm need found value ..s1,S2,s3,...and fmin ,Fmin represents the lowest cost

**Comment by odow** [comment]
What variables belong to the upper level? What variables belong to the lower level? Is F the upper objective or the lower objective?

Try following the documentation here: https://joaquimg.github.io/BilevelJuMP.jl/stable/tutorials/getting_started/

**Comment by joaquimg** [comment]
Hello,
The main unspecified point is: which variables belong to the leader and which ones belong to the follower?

**Comment by OthmanProgramming** [comment]
> Hello,
> The main unspecified point is: which variables belong to the leader and which ones belong to the follower?

I have two levels. The higher level called the leader is responsible for finding the lowest cost realization (Estimated required costs), while the lowest level is called the dependent and is responsible for the cameras and prices set by the drug importing company (the lowest realized cost) of the import costs... while the variables are below

**Comment by OthmanProgramming** [comment]
> Hello,
> The main unspecified point is: which variables belong to the leader and which ones belong to the follower?Variables represent the optimum for each drug for three types of drugs ،Three types of medication.. s1,S2,s3,,
It is dependent on the two levels, meaning there are no higher and lower level variables..all of them are for each level..I need to find values S1، S2، S3،It represents the optimal quantity required for each drug... and was found Fmin The required quantities and prices are the highest level...and fmin Quantities and prices set by the importing company Import costs

**Comment by joaquimg** [comment]
Unfortunately,
What you describe does not seem to fit in this framework that requires variables to belong to some of the levels. Note that a variable that belongs to a level might appear in the other.
"Belong" means which level is optimising that variable.

If this is not clear I recommend this tutorial: https://optimization-online.org/wp-content/uploads/2021/06/8450-1.pdf

If you have a reference for what you are doing it might be useful for others to help you.

**Comment by joaquimg** [comment]
I will close as there seems to be no update. Feel free to reopen if there are any news.
