### ISSUE TITLE
BilevelJuMP is restricted to v0.5.2 on windows while is installed normally to v0.6.2 on linux

### ISSUE THREAD

**Issue by totooqiao** [joaquimg/BilevelJuMP.jl#212]
When trying to install BilevelJuMP on Windows, it's limited to version 0.5.2, and it shows that updates are available, but I cannot update to version 0.6.2. However, on the Linux platform, I can install version 0.6.2. I'm not sure where the issue is coming from.

**Comment by odow** [comment]
What is the output if you do `] add BilevelJuMP@0.6.2` in the package manager?

**Comment by odow** [comment]
The last CI job installed and passed tests with 0.6.2 on Windows: https://github.com/joaquimg/BilevelJuMP.jl/actions/runs/5913458217/job/16037874116

So you likely have a different package that is holding you back.

**Comment by totooqiao** [comment]
It gives me the following log, is there a package installation that's causing version conflicts?

(@v1.8) pkg> add BilevelJuMP@0.6.2
    Updating registry at `D:\Julia-1.8.2\juliaPKG\registries\General.toml`
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Optim [429524aa]:
 Optim [429524aa] log:
 ├─possible versions are: 0.15.3-1.7.8 or uninstalled
 ├─restricted by compatibility requirements with TrafficAssignment [735ffce8] to versions: [0.16.0, 0.20.0-0.21.0]
 │ └─TrafficAssignment [735ffce8] log:
 │   ├─possible versions are: 0.5.0-0.6.3 or uninstalled
 │   ├─restricted to versions * by an explicit requirement, leaving only versions 0.5.0-0.6.3 
 │   └─restricted by compatibility requirements with DataFrames [a93c6f00] to versions: 0.5.0-0.5.1 or uninstalled, leaving only versions: 0.5.0-0.5.1
 │     └─DataFrames [a93c6f00] log:
 │       ├─possible versions are: 0.11.7-1.6.1 or uninstalled
 │       ├─restricted to versions * by an explicit requirement, leaving only versions 0.11.7-1.6.1
 │       ├─restricted by compatibility requirements with Reexport [189a3867] to versions: 0.22.3-1.6.1 or uninstalled, leaving only versions: 0.22.3-1.6.1
 │       │ └─Reexport [189a3867] log:
 │       │   ├─possible versions are: 0.2.0-1.2.2 or uninstalled
 │       │   └─restricted by compatibility requirements with BilevelJuMP [485130c0] to versions: 1.0.0-1.2.2
 │       │     └─BilevelJuMP [485130c0] log:
 │       │       ├─possible versions are: 0.1.0-0.6.2 or uninstalled
 │       │       └─restricted to versions 0.6.2 by an explicit requirement, leaving only versions 0.6.2
 │       ├─restricted by compatibility requirements with PrettyTables [08abe8d2] to versions: 
[0.11.7-0.21.8, 0.22.4-1.6.1] or uninstalled, leaving only versions: 0.22.4-1.6.1
 │       │ └─PrettyTables [08abe8d2] log:
 │       │   ├─possible versions are: 0.1.0-2.2.8 or uninstalled
 │       │   ├─restricted by compatibility requirements with Reexport [189a3867] to versions: 
[0.1.0-0.2.1, 0.11.0-2.2.8] or uninstalled
 │       │   │ └─Reexport [189a3867] log: see above
 │       │   └─restricted by compatibility requirements with DataFrames [a93c6f00] to versions: 0.10.0-1.3.1, leaving only versions: 0.11.0-1.3.1
 │       │     └─DataFrames [a93c6f00] log: see above
 │       └─restricted by compatibility requirements with Compat [34da2185] to versions: 0.11.7-1.3.6 or uninstalled, leaving only versions: 0.22.4-1.3.6
 │         └─Compat [34da2185] log:
 │           ├─possible versions are: 1.0.0-4.10.0 or uninstalled
 │           ├─restricted by julia compatibility requirements to versions: 2.0.0-4.10.0 or uninstalled, leaving only versions: 2.0.0-4.10.0
 │           ├─restricted by compatibility requirements with LNR [7c4cb9fa] to versions: 1.0.0-3.46.2, leaving only versions: 2.0.0-3.46.2
 │           │ └─LNR [7c4cb9fa] log:
 │           │   ├─possible versions are: 0.2.0-0.2.1 or uninstalled
 │           │   └─restricted by compatibility requirements with Compat [34da2185] to versions: 0.2.1 or uninstalled, leaving only versions: 0.2.1
 │           │     └─Compat [34da2185] log: see above
 │           └─restricted by compatibility requirements with DataFrames [a93c6f00] to versions: 3.17.0-4.10.0, leaving only versions: 3.17.0-3.46.2
 │             └─DataFrames [a93c6f00] log: see above
 ├─restricted by compatibility requirements with Compat [34da2185] to versions: 0.17.2-1.7.8 or uninstalled, leaving only versions: 0.20.0-0.21.0
 │ └─Compat [34da2185] log: see above
 └─restricted by compatibility requirements with TrafficAssignment [735ffce8] to versions: 0.16.0 — no versions left
   └─TrafficAssignment [735ffce8] log: see above

**Comment by odow** [comment]
The problem appears to be https://github.com/chkwon/TrafficAssignment.jl. 

If you remove it, you should be able to install a newer version of BIlevelJuMP.

Note that https://github.com/chkwon/TrafficAssignment.jl hasn't been updated for a couple of years.

**Comment by totooqiao** [comment]
yes, after removing it, the latest version of BilvelJuMP is installed.
Thank you @odow
