### ISSUE TITLE
Use JuMP complementarity constraints

### ISSUE THREAD

**Issue by joaquimg** [joaquimg/BilevelJuMP.jl#4]
This allows passing the problem to:
KNITRO
PATHSolver

**Comment by AliRafieePour** [comment]
Hey,

Do you have any idea whether we can use this BilevelJuMP to model MINLP bilevel problems as the GAMS EMP solver do?

**Comment by joaquimg** [comment]
Hi!
Not sure this issue is te correct spot for this question, but can you post an example?
