### ISSUE TITLE
Bug in using set_start_value

### ISSUE THREAD

**Issue by davide-f** [joaquimg/BilevelJuMP.jl#67]
I am experiencing problems in setting initial values for the optimizations, aiming to speed up the calculations.

ERROR: LoadError: In `MathOptInterface.ScalarAffineFunction{Float64}`-in-`MathOptInterface.EqualTo{Float64}` constraint: Constant 1.0 of the function is not zero. The function constant should be moved to the set. You can use `MOI.Utilities.normalize_and_add_constraint` which does this automatically.

This error occurs as in the attached file.
[report_error.txt](https://github.com/joaquimg/BilevelJuMP.jl/files/4892078/report_error.txt)

**Comment by davide-f** [comment]
I tried to better understand the error and I believe it should be related to the starting value of the variables of the lower level problem.

The following simplified code still generates the problem and it is created by the fact that an affine function in the MOI representation that was supposed to have constant == 0, actually the constant equals -0.5, which represents the starting value of the algorithm. The same does not occur for the upper problem, instead.
[error_code.txt](https://github.com/joaquimg/BilevelJuMP.jl/files/4931148/error_code.txt)

**Comment by joaquimg** [comment]
@davide-f , excellent job! the actual error was in `get_canonical_complement` but your suggestion led me straight to it. working on a fix
