### ISSUE TITLE
Error using value with expressions (appeared with new release)

### ISSUE THREAD

**Issue by davide-f** [joaquimg/BilevelJuMP.jl#72]
Dear developers,

In the use of the new version I discovered that the value function does not work anymore with expressions, like the ones shown in the following code.
In the version 0.1.0 of BilevelJuMP they were working perfectly, now that I updated my repository it doesn't work anymore (it may be related also to the upgrade of JuMP). I hope it should be easy and fast to solve.

[error_source.txt](https://github.com/joaquimg/BilevelJuMP.jl/files/4973418/error_source.txt)

I realized that this is the same issue of #70 ; the attached source code can be a detailed example

The problem is caused mainly  at line 155 of file aff_expr of JuMP because the returned value of function promote_op becomes "union" instead of Float64. I crosschecked it with a similar example developed in JuMP only.

**Comment by davide-f** [comment]
After some debug, I discovered that probably the problem is originated by the new update of JuMP package, in which developers added the option "result" to the value function as in value(VariableRef, result=1), which is used to retrive additional results other than the last optimal one.
I have solved this issue by adding the option "result" value(BilevelVariableRef, result) with the code reported below.

function JuMP.value(v::BilevelVariableRef; result::Int = 1)::Float64
    m = owner_model(v)
    solver = m.solver
    ref = solver_ref(v)
    return MOI.get(solver, MOI.VariablePrimal(result), ref)
end

I believe that this additional feature may affect also other functions.

**Comment by joaquimg** [comment]
the code:
```julia
using JuMP, BilevelJuMP, Gurobi

m = BilevelModel(Gurobi.Optimizer, mode = BilevelJuMP.SOS1Mode())

@variable(Upper(m), 0 <= x <= 3 )
@variable(Lower(m), 0 <= y[1:2])
@variable(Lower(m), 0 <= z[1:2])

a = JuMP.Containers.DenseAxisArray([y[i]+ z[i] for i = 1:2], 1:2)
d = JuMP.Containers.SparseAxisArray(Dict((1, i) => y[i] for i in 1:2))

c = y[1] + y[2]

@constraint(Upper(m), x >=1)

@constraint(Lower(m), y[1] >= 0.5)
@constraint(Lower(m), y[2] >= 0.5)

@objective(Upper(m), Min, x)

@objective(Lower(m), Min, y[1]+z[2])

optimize!(m)


_a = value.(a)
_c = value.(c)
_d = value.(d)

```
