### ISSUE TITLE
Automate start point for additional constraints

### ISSUE THREAD

**Issue by joaquimg** [joaquimg/BilevelJuMP.jl#78]
x-ref: https://github.com/joaquimg/BilevelJuMP.jl/pull/76#issuecomment-666298425

**Comment by davide-f** [comment]
I have been working on this point, may I be of any practical help?
I am completely available to collaborate if I can be of any help

**Comment by davide-f** [comment]
I have developed some code to evaluate the extreme values of the bounds so to be able to initialize the binary constraint in the fortunyamat formulation. I don't know if it can be of help. I am working on it

**Comment by joaquimg** [comment]
Nice!
It seems that you have code that might be very useful.

Feel free to open Pull Requests with proposed changes, it would be very welcome!

I recommend one change per PR, i.e., one for bounds and a separate one for initialization.
These should be accompanied by tests so that we guarantee that they won't be broken by other implementations.

**Comment by joaquimg** [comment]
Partially solved by #91 
Still require to test dual information (#36).

**Comment by joaquimg** [comment]
closed by #103
