### ISSUE TITLE
Simple fix: get_optimizer_attribute

### ISSUE THREAD

**Issue by davide-f** [joaquimg/BilevelJuMP.jl#80]
Dear developer,

In the implementation of JuMP.set_optimizer_attribute(bm::BilevelModel, name::String, value),

The line: return JuMP.set_optimizer_attribute(bm.solver, MOI.RawParameter(name), value)

should be changed in

return JuMP.set_optimizer_attribute(bm, MOI.RawParameter(name), value)

I get the following error with the first formulation, but with the little changeit works fine.
error ERROR: MethodError: no method matching get_optimizer_attribute(::MathOptInterface.Bridges.LazyBridgeOptimizer{Gurobi.Optimizer}, ::MathOptInterface.RawParameter)

**Comment by joaquimg** [comment]
you look right.
Do you want to open a PR?

**Comment by davide-f** [comment]
I would definitely like to but I may not have write permissions, I cannot create branches if that's what you mean
