### ISSUE TITLE
Refuse s2->s1)

### ISSUE THREAD

**Issue by davide-f** [joaquimg/BilevelJuMP.jl#81]
Dear developer,

I am not sure whether in the cited line below, there occurs a refuse: might s2 be s1? Although s1 has the same value of s2.

https://github.com/joaquimg/BilevelJuMP.jl/blob/c8594fb98a1711e5f0b735dfaa3f87cc58d18333/src/moi.jl#L770

**Comment by joaquimg** [comment]
This should be fixed on master branch
