### ISSUE TITLE
Error when trying conic lower level with Ipopt

### ISSUE THREAD

**Issue by alejandroowen** [joaquimg/BilevelJuMP.jl#95]
I tried the following code I found in the readme:

`IPO_OPT = Ipopt.Optimizer`
`IPO = MOI.Bridges.Constraint.SOCtoNonConvexQuad{Float64}(IPO_OPT)`
`BilevelModel(IPO, mode = BilevelJuMP.ProductMode(1e-5))`

And I get the following error:

![image](https://user-images.githubusercontent.com/69917992/107440931-6f849a80-6b02-11eb-8742-8c0ddf9c43fa.png)

Any help would be appreciated. Thanks

**Comment by joaquimg** [comment]
sorry for that, please replace:
`IPO_OPT = Ipopt.Optimizer`
by
`IPO_OPT = Ipopt.Optimizer()`

**Comment by joaquimg** [comment]
readme is actually correct.

**Comment by alejandroowen** [comment]
The reason why I changed the `Ipopt.Optimizer()` to just `Ipopt.Optimizer` is because  I otherwise get this error:

![image](https://user-images.githubusercontent.com/69917992/107551016-bd031500-6b9f-11eb-8d3f-f7d9b321c5d4.png)

**Comment by joaquimg** [comment]
That is another issue.
Can you open a new one and post your minimal example so I can reproduce here?

**Comment by alejandroowen** [comment]
will do
